### ISSUE TITLE
`rasterstats` package not installed

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#52]
The `rasterstats` package is missing so at the moment the book does not render on GitHub. I'm not sure how to solve this, I guess that RUN pip3 install `rasterstats` needs to be added to https://github.com/geocompr/docker/edit/master/python/Dockerfile ?

**Comment by Robinlovelace** [comment]
Yes, probably. I'll give it a go. Thanks for forging ahead with this Michael!

**Comment by Robinlovelace** [comment]
See commit above @michaeldorman, hopefully that fixes it.

**Comment by Robinlovelace** [comment]
More broadly, can this be added to the requirements file? Looking here it seems `rasterstats` is not there: https://github.com/geocompr/py/search?q=rasterstats

**Comment by Robinlovelace** [comment]
Please update this https://github.com/geocompr/py/blob/main/environment.yml if you get a chance Michael, can do it but you may have other ones to add here. Long term, that could allow us to use the dependencies from that file to inform the packages to install in the Docker images reducing maintenance time by having all dependencies in one place.

**Comment by michaeldorman** [comment]
Thanks, I updated https://github.com/geocompr/py/blob/main/environment.yml

**Comment by Robinlovelace** [comment]
Given issues here https://github.com/geocompr/docker/issues/26 I think it's time to try building a docker image on conda: https://hub.docker.com/r/continuumio/miniconda3 I'll open another issue in the docker repo.

**Comment by Robinlovelace** [comment]
This is fixed in a more future proof way in #56. Next time the workflow in `main.yml` fails I suggest we put the code in the conda yml file in there and deprecate use of the geocompy image or maybe make the geocompy image based on conda. Thoughts welcome. For now, good riddance to these packaging issues for the foreseeable, any new packages in environment.yml should get picked up by the docker container automatically (although maybe not instantly).
